# -*- coding: utf-8 -*-
"""Github-Demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pFE9NucMCwu83JjL_FKYA5jCrTrWpKSG
"""

#Use this code for the git-demo
#write your name

name = "PRACHI NERKAR"

print("I love Chicago")
print("East or West, Pallu is the Best")

print("Tejas commiting changes to test")
